### ISSUE TITLE
quotation marks are not (always?)escaped, particularly ggplot

### ISSUE THREAD

**Issue by o-jasper** [blegat/git-dot#1]
[github.com/yhat/ggpy](https://github.com/yhat/ggpy), version b6d23c22d52557b983da8ce7a3a6992501dadcd6, for instance.

**Comment by blegat** [comment]
Could you be more specific of what's the issue ?

**Comment by o-jasper** [comment]
The program runs perfectly fine, and outputs a `.dot` file, but if comments contain `"`-quotes themselves, it produces them in the `.dot` file unescaped, and running `dot` on them gives an error like this:

    Error: ggpy.dot: syntax error in line 272 near '"'
    [1]    10114 exit 1     dot ggpy.dot

**Comment by o-jasper** [comment]
See PR #2 .. [Just `.replace` in line 110](https://github.com/blegat/git-dot/pull/2/files#diff-e33e744137b6a9fa8d278ddba6f632e4L110).
